// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WhatsMS_Broker.Data.Context;

#nullable disable

namespace WhatsMS_Broker.Data.Migrations
{
    [DbContext(typeof(BrokerDbContext))]
    [Migration("20250513224806_Iniciando")]
    partial class Iniciando
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("WhatsMS_Broker.Domain.Entidades.AccountMS", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AuthToken")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("auth_token");

                    b.Property<string>("ClientName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("client_name");

                    b.Property<string>("ClientSessionID")
                        .HasColumnType("text")
                        .HasColumnName("client_session_id");

                    b.Property<int>("ClienteMSId")
                        .HasColumnType("integer")
                        .HasColumnName("cliente_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_active");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("phone_number");

                    b.Property<int>("PortRun")
                        .HasMaxLength(10)
                        .HasColumnType("integer")
                        .HasColumnName("port_run");

                    b.Property<string>("QrCodeBase64")
                        .HasColumnType("text")
                        .HasColumnName("qrcode_base64");

                    b.Property<string>("SessionName")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("session_name");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("WebhookUrl")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("webhook_url");

                    b.HasKey("Id");

                    b.HasIndex("ClienteMSId");

                    b.ToTable("tb_accounts", (string)null);
                });

            modelBuilder.Entity("WhatsMS_Broker.Domain.Entidades.ClienteMS", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("email");

                    b.Property<string>("NameUser")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name_user");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("password");

                    b.HasKey("Id");

                    b.ToTable("tb_clientes", (string)null);
                });

            modelBuilder.Entity("WhatsMS_Broker.Domain.Entidades.MessageInbound", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AccountId")
                        .HasColumnType("integer")
                        .HasColumnName("account_id");

                    b.Property<string>("Author")
                        .HasColumnType("text")
                        .HasColumnName("author");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<DateTime>("DateReceived")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_received")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int?>("ForwardingScore")
                        .HasColumnType("integer")
                        .HasColumnName("forwarding_score");

                    b.Property<string>("FromNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("from_number");

                    b.Property<string>("IdMessageWhatsApp")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("id_message_whatsApp");

                    b.Property<bool>("IsColetado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_coletado");

                    b.Property<bool>("IsForwarded")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_forwarded");

                    b.Property<bool>("IsGroup")
                        .HasColumnType("boolean")
                        .HasColumnName("is_group");

                    b.Property<double?>("Latitude")
                        .HasColumnType("decimal(10, 6)")
                        .HasColumnName("latitude");

                    b.Property<double?>("Longitude")
                        .HasColumnType("decimal(10, 6)")
                        .HasColumnName("longitude");

                    b.Property<string>("MessageType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("message_type");

                    b.Property<string>("MidiaContentType")
                        .HasColumnType("text")
                        .HasColumnName("midia_content_type");

                    b.Property<string>("MidiaURL")
                        .HasColumnType("text")
                        .HasColumnName("midia_url");

                    b.Property<string>("NotifyName")
                        .HasColumnType("text")
                        .HasColumnName("notify_name");

                    b.Property<string>("ProfileName")
                        .HasColumnType("text")
                        .HasColumnName("profile_name");

                    b.Property<string>("ToNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("to_number");

                    b.Property<string>("Type")
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("DateReceived");

                    b.ToTable("tb_message_inbound", (string)null);
                });

            modelBuilder.Entity("WhatsMS_Broker.Domain.Entidades.MessageOutbound", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AccountId")
                        .HasColumnType("integer")
                        .HasColumnName("account_id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("FromNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("from_number");

                    b.Property<string>("IdMsg")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("id_msg");

                    b.Property<bool>("IsGroup")
                        .HasColumnType("boolean")
                        .HasColumnName("is_group");

                    b.Property<double?>("Latitude")
                        .HasColumnType("decimal(10, 6)")
                        .HasColumnName("latitude");

                    b.Property<double?>("Longitude")
                        .HasColumnType("decimal(10, 6)")
                        .HasColumnName("longitude");

                    b.Property<string>("MessageType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("message_type");

                    b.Property<string>("MidiaContentType")
                        .HasColumnType("text")
                        .HasColumnName("midia_content_type");

                    b.Property<string>("MidiaURL")
                        .HasColumnType("text")
                        .HasColumnName("midia_url");

                    b.Property<DateTime>("SentAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("sent_at");

                    b.Property<int>("StatusId")
                        .HasColumnType("integer")
                        .HasColumnName("status_id");

                    b.Property<string>("ToNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("to_number");

                    b.Property<string>("Type")
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("StatusId");

                    b.ToTable("tb_message_outbound", (string)null);
                });

            modelBuilder.Entity("WhatsMS_Broker.Domain.Entidades.MessageStatus", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("descricao");

                    b.HasKey("Id");

                    b.ToTable("tb_message_status", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 0,
                            Descricao = "Pendente"
                        },
                        new
                        {
                            Id = 1,
                            Descricao = "Enviada"
                        },
                        new
                        {
                            Id = 2,
                            Descricao = "Entregue"
                        },
                        new
                        {
                            Id = 3,
                            Descricao = "Lida"
                        },
                        new
                        {
                            Id = 4,
                            Descricao = "Falhou"
                        });
                });

            modelBuilder.Entity("WhatsMS_Broker.Domain.Entidades.AccountMS", b =>
                {
                    b.HasOne("WhatsMS_Broker.Domain.Entidades.ClienteMS", "ClienteMS")
                        .WithMany("Accounts")
                        .HasForeignKey("ClienteMSId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ClienteMS");
                });

            modelBuilder.Entity("WhatsMS_Broker.Domain.Entidades.MessageInbound", b =>
                {
                    b.HasOne("WhatsMS_Broker.Domain.Entidades.AccountMS", "Account")
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("WhatsMS_Broker.Domain.Entidades.MessageOutbound", b =>
                {
                    b.HasOne("WhatsMS_Broker.Domain.Entidades.AccountMS", "Account")
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WhatsMS_Broker.Domain.Entidades.MessageStatus", "Status")
                        .WithMany("MessageOutbounds")
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Account");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("WhatsMS_Broker.Domain.Entidades.ClienteMS", b =>
                {
                    b.Navigation("Accounts");
                });

            modelBuilder.Entity("WhatsMS_Broker.Domain.Entidades.MessageStatus", b =>
                {
                    b.Navigation("MessageOutbounds");
                });
#pragma warning restore 612, 618
        }
    }
}
